from tkinter import *
def show():
    n=int(v1.get())
    v2.set(bin(n))
    v3.set(oct(n))
    v4.set(hex(n))
window=Tk()
window.geometry("300x400")
v1=StringVar()
v2=StringVar()
v3=StringVar()
v4=StringVar()
l1=Label(window,text="Enter Number:")
l1.pack()
t1=Entry(window,textvariable=v1)
t1.pack()
l2=Label(window,text="Binary:")
l2.pack()
t2=Entry(window,textvariable=v2)
t2.pack()
l3=Label(window,text="Octal:")
l3.pack()
t3=Entry(window,textvariable=v3)
t3.pack()
l4=Label(window,text="Hexa Decimal:")
l4.pack()
t4=Entry(window,textvariable=v4)
t4.pack()
b1=Button(window,text="OK", command=show)
b1.pack()
window.mainloop()
