from tkinter import *
def show():
    a=s1.get()
    a=a.upper()
    s2.set(a)
window=Tk()
window.geometry("300x400")
s1=StringVar()
s2=StringVar()
l1=Label(window,text="Enter String:")
l1.pack()
t1=Entry(window,textvariable=s1)
t1.pack()
l2=Label(window,text="UpperCase:")
l2.pack()
t2=Entry(window,textvariable=s2)
t2.pack()
b1=Button(window,text="UpperCase", command=show)
b1.pack()
window.mainloop()
